### ISSUE TITLE
try.goodtables not working with uploaded files

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables.io#296]

**Comment by Stephen-Gates** [comment]
Oh Cool! Does this mean I can specify a Data Package instead of a Schema on this page?

<img width="789" alt="screenshot 2018-02-22 06 48 45" src="https://user-images.githubusercontent.com/9379524/36504535-9011206e-179c-11e8-9229-ea78b39be57a.png">

If so that will reduce the need to address https://github.com/frictionlessdata/example-data-packages/issues/12

**Comment by vitorbaptista** [comment]
@Stephen-Gates yes, that should be working now. If you upload a datapackage.json as the source, it'll get the schema from it, and in general do what you would expect. A zipped data package still doesn't work, so it will only validate remote files, but we'll add support for that as well (see #298)
