### ISSUE TITLE
Internal server error on constraints

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [frictionlessdata/goodtables.io#302]
In the tableschema-specification at frictionless.io it is clearly stated which constraints apply where. For instance a 'pattern' only applies to an 'string'.  I haven't compared them all but this case is different from xsd-patterns ans as it happend we fed the goodtables-api with an integer-field containing a pattern-constraint. It gave an internal server error. I had to discover the hard way  what caused it.  I would be nice to include  a check on the tableschema-specifications in the api.

**Comment by vitorbaptista** [comment]
Thanks for the report, I agree this would be an improvement for our validations. I created an issue on https://github.com/frictionlessdata/specs/issues/612, as this issue is related to the JSON Schemas created in that repository.

**Comment by ezwelty** [comment]
@vitorbaptista Actually, I would suggest that goodtables skip trying to apply constraints to unsupported field types (rather than crashing) and log the incident as a warning or error. That way, goodtables could co-exist with custom checks that do, for example, implement a pattern constraint on an integer field.
