### ISSUE TITLE
Autodiscover tasks from plugins

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#34]
Celery has the option of autodiscovering tasks in a module, we just need to pass it the module list on which to find them, ie go from this (what we are doing now):

```python
app.autodiscover_tasks(['goodtablesio.plugins.github'])
```

to this:

```python
app.autodiscover_tasks(['goodtablesio.plugins.{0}'.format(p) for p in get_plugins()])
```

or similar.

**Comment by pwalsh** [comment]
@amercader can you write a mini spec for this.

**Comment by amercader** [comment]
Done, this should be straight-forward

**Comment by roll** [comment]
For now proposed way is to have:

> goodtablesio.__init__.py
```python

# ...

# Register plugins
import goodtablesio.plugins.github
```

> goodtablesio.plugins.github.__init__.py
```python

# Register models
import goodtablesio.plugins.github.models.repo

# Register tasks
import goodtablesio.plugins.github.tasks.jobconf
import goodtablesio.plugins.github.tasks.repos

# Register signals
import goodtablesio.plugins.github.signals
```

Because in our core codebase we will be having pretty manageable amount of plugins this way seems pretty enough to keep things simple. Also against autodiscovering tasks says that we also need to register our signals, models (for autogenerating migrations) etc so this unified method for register things seems more suitable for the project in general.

CLOSING for now (please re-open if there is other thoughts)
