### ISSUE TITLE
Report storage

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#4]
# Description

A *goodtables.io* job ultimately outputs a **report**. These reports should be saved as static JSON on an S3 bucket, and with folder naming conventions that make it easy to retrieve based on the *job identifier* and the *user identifier*.

# Tasks

- [ ] Upload reports to S3 after a validation job finishes
- [ ] Provide an API to access these reports (part of #8)

# Estimate

0.5

**Comment by roll** [comment]
@pwalsh 
@amercader 
Is it only for MVP or it's a more long term plan? If second I have a concern about relying to much on S3. Of course we should store files there but for report storage we could also use a relational db. I suppose for project like this we will setup db anyway at some point. And celery have a native support to put job results to sql database. WDYT?

**Comment by pwalsh** [comment]
long term plan.

For me, S3 is much better for long term (low costs, redundant in terms of data versioning and general availability), so I'm curious as to why you think it is good short term, but not long term.

**Comment by roll** [comment]
Just thinking about architecture overall for now not fully understand why to store one entities outside of db. Because I suppose we'll be having db anyway for users etc.

Consider e.g. API has got a request to return users last 20 runs. It could be in API to respond one sql query or one sql query + 20 http queries if we use s3 (correct me if i wrong). Also we will be dealing with concurent writes, may be report sttucture migrations etc. Database is just  a first thing comming to mind to solve it.

Just thinking at lound. I guess I could miss something against db - just diving into architecture.

**Comment by pwalsh** [comment]
Up to @amercader I guess. we are storing files anyway, and this is simply a son object that will never change.

I agree that eventually we will need a DB for users.

**Comment by amercader** [comment]
I agree with @roll. Any functionality more complex than individual links to reports will require some sort of persistent storage (db): task list for a user, list repos/integrations enabled per user, ...
For the MVP we can definitely get away with S3 but long term I don't think so. Let's decide once we flesh out more the API and user stories needed for second stage.

**Comment by roll** [comment]
@amercader 
If we will go with database it will be completed by #13 and PR for #8.

**Comment by amercader** [comment]
For MVP we are storing the JSON reports in Postgres. We can assess S3 when we move to the next stage
