### ISSUE TITLE
Create source and integration models

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#96]
# Overview

For now we have concepts for:
- plugin
- job

Between this two levels there should be something like project/resource (github repo, s3 folder etc) to run multiple jobs against.

This blocks #66 I suppose.

cc @amercader

**Comment by amercader** [comment]
I agree that we should define a name for this entity (I prefer `source` but this might clash with goodtables terminology) but do we need an actual model entity for this? They can be different depending on the integration so it would be hard to model a generic entity for all. Perhaps having a common base with just. Should each integration define its own source model like you did for `GithubRepo`? name and extend them

Why do you think it blocks #66, just in terms on structuring the information in the UI?

**Comment by roll** [comment]
About #66:
- ```can view whole history of reports for that job``` - it requires link between project/source and job

**Comment by roll** [comment]
I use `project` term for now because in my opinion it seems a good choice - user usese `goodtables.io` creating projects for validation like github_repo, s3_folder etc (cc @pwalsh). But we have other options like `source` etc.

---

@amercader 
So we have two options:
- use entities like `github_repo`, `s3_folder` etc 
  - PROS: strict data types on table levels
  - CONS: we need to connect all of them to jobs and users (could be very tricky)
- use unified entity `project` with `plugin_name: TEXT` and `plugin_data: JSON`
  - PROS: first-class database integrity (relations with users and jobs) without hacks
  - CONS: using JSON for data (like repo's owner/name/active) is always more problematic in RDBMS

For now I more like the 2 options. So our ER-model could look like this:
![goodtables io](https://cloud.githubusercontent.com/assets/557395/21886236/f2caf704-d8cb-11e6-915d-a8aa68d646ff.png)

Where project is the most important entity wich have many jobs against it. And in many-to-many relationships with users. Later we could create user roles on projects (like invite user to watch status of my dropbox project validations)

**Comment by roll** [comment]
And for #64 we could go for something like this:

![goodtables io 1](https://cloud.githubusercontent.com/assets/557395/21887122/adeddd6e-d8cf-11e6-9fc5-a50accc1c941.png)

**Comment by amercader** [comment]
I like 2 more as well. It will allow to abstract the logic to display all jobs for a particular plugin easier. We can always create views to simplify queries if the JSON data gets too complicated, but I doubt it. Most projects will only have a name or maybe an account/org as well. `active` could be a first level field as is an internal GTIO flag. BTW I like `source` more (as in this is the source of files to validate) but I don't mind it too much.

I'm not entirely sure if we need to track all relations between all users and their projects, at least for Github (it may make sense on S3). Say I set up 2 repos on the frictionlessdata org and then you, paul or anyone from OKI logs in. They would expect to be shown the FD jobs I started just because they belong to the same org on Github. If we wanted to check at the repo level they would need to sync the account first to get all repos. My only concern is this initial syncing and having to store all repos for all users on the system (and keep them up to date).

**Comment by pwalsh** [comment]
@amercader @roll 

Agreed user terminology:

- *User*: the representation of a person inside the system. Users get authenticated, and authorized to act
- *Integration*: the representation of a connection between goodtables and another web-accessible service that can host files that goodtables can validate.
- *Source*: a self-contained entity, accessible via an *Integration*, that holds files that can be validated by goodtables
- *Job*: the user-facing unit of work that goodtables performs for the user on a repository.

These terms will be part of the UI as needed. Other concepts are up to implementing team as you see fit.

**Comment by pwalsh** [comment]
@amercader assigned to you for scoping and estimate.
